---
image: docker:latest

stages:
  - preflight
  - check
  - deploy

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

# Generic preflight template
.preflight: &preflight
  stage: preflight
  tags:
    - preflight

# Generic ESPHome template
.esphome: &esphome
  stage: check
  variables:
    PYTHONPATH: "/usr/src/app:$PYTHONPATH"
  before_script:
    - esphome dummy.yaml version
    # secrets is used in common
    - cp ./.stubs/secrets.yaml ./common/
    # secrets is used in root
    - cp ./.stubs/secrets.yaml ./
  script:
    - |
      for file in $(find \
        ./ \
        -maxdepth 1 \
        -type f \
        -name "*.yaml"\
        -not -name "secrets.yaml"
        ); do
        echo "Config validation for $file"
        esphome $file config
      done
  tags:
    - config

# Generic deployment template
.esphome-deploy: &esphome-deploy
  stage: deploy
  variables:
    PYTHONPATH: "/usr/src/app:$PYTHONPATH"
  image:
    name: esphome/esphome:latest
    entrypoint: [""]
  before_script:
    - apt update && apt install -y git-crypt openssl
    - |
      openssl enc -aes-256-cbc -pbkdf2 -d -in git-crypt.key.enc -out \
          git-crypt.key -k $OPENSSL_PASSPHRASE
    - git-crypt unlock git-crypt.key
    - esphome dummy.yaml version
  after_script:
    - rm -f git-crypt.key
  retry: 2
  tags:
    - esphome

# Preflight jobs
shellcheck:
  <<: *preflight
  image:
    name: koalaman/shellcheck-alpine:stable
    entrypoint: [""]
  before_script:
    - shellcheck --version
    - apk --no-cache add grep
    - |
      find . -type f -print0 | \
        xargs -0 sed -i 's:#!/usr/bin/with-contenv bash:#!/bin/bash:g'
  script:
    - |
      for file in $(grep -IRl "#\!\(/usr/bin/env \|/bin/\)" --exclude-dir ".git" "${ADDON_TARGET}"); do
        if ! shellcheck $file; then
          export FAILED=1
        else
          echo "$file OK"
        fi
      done
      if [ "${FAILED}" = "1" ]; then
        exit 1
      fi

yamllint:
  <<: *preflight
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
    # secrets is used in common
    - cp ./.stubs/secrets.yaml ./common/
    # secrets is used in root
    - cp ./.stubs/secrets.yaml ./
  script:
    - yamllint .

jsonlint:
  <<: *preflight
  image: sahsu/docker-jsonlint
  before_script:
    - jsonlint --version || true
  script:
    - |
      for file in $(find . -type f -name "*.json"); do
        if ! jsonlint -q $file; then
          export FAILED=1
        else
          echo "$file OK"
        fi
      done
      if [ "${FAILED}" = "1" ]; then
        exit 1
      fi

markdownlint:
  <<: *preflight
  image:
    name: ruby:alpine
    entrypoint: [""]
  before_script:
    - gem install mdl
    - mdl --version
  script:
    - mdl --style all --warnings .

# ESPHome test jobs
esphome-latest:
  <<: *esphome
  image:
    name: esphome/esphome:latest
    entrypoint: [""]

esphome-beta:
  <<: *esphome
  image:
    name: esphome/esphome:beta
    entrypoint: [""]
  allow_failure: true

# Deployment jobs
led_bureau:
  <<: *esphome-deploy
  script:
    - esphome led_bureau.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - led_bureay.yaml
      - secrets.yaml
      - common/*.{yaml}

weatherstation:
  <<: *esphome-deploy
  script:
    - esphome weatherstation.yaml run --no-logs
  only:
    refs:
      - master
    changes:
      - weatherstation.yaml
      - secrets.yaml
      - common/*.{yaml}