substitutions:
  device: cabinet_fan
  name: Cabinet Fan
  update_interval: 10min
esphome:
  name: ${device}
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret lan_domain

logger:

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/web_server.yaml
<<: !include common/text_sensors.yaml
<<: !include common/binary_sensor.yaml
<<: !include common/switch.yaml

dallas:
  - pin: D2

sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml
  - platform: dallas
    address: 0x8F02131211EFAA28
    name: "Cabinet Temperature"

output:
  - platform: esp8266_pwm
    pin: D1
    frequency: 25000 Hz
    id: fanout_1
  - platform: esp8266_pwm
    pin: D3
    frequency: 25000 Hz
    id: fanout_2

fan:
  - platform: speed
    output: fanout_1
    name: ${name}_1
  - platform: speed
    output: fanout_2
    name: ${name}_2