---
substitutions:
  device: garage
  name: Garage
  update_interval: 10min

esphome:
  name: ${device}
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret lan_domain
  manual_ip:
    static_ip: 192.168.0.200
    gateway: 192.168.0.1
    subnet: 255.255.255.0

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/web_server.yaml
<<: !include common/text_sensors.yaml
<<: !include common/logger.yaml
<<: !include common/binary_sensor.yaml
<<: !include common/switch.yaml

dallas:
  - pin: D5

sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml
  - platform: dallas
    address: 0x8F02131211EFAA28
    name: "Garage Temperature"
