---
substitutions:
  device: led_schouw
  name: Led Schouw
  alt_name: Living
  update_interval: 10min

esphome:
  name: ${device}
  platform: ESP8266
  board: d1_mini

<<: !include common/common.yaml
<<: !include common/logger.yaml
<<: !include common/switch.yaml

# status_led:
#   pin: D4

binary_sensor:
  - !include common/binary_sensor/status.yaml
  - platform: gpio
    pin: D5
    name: "Motion ${alt_name}"
    device_class: motion

sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml
  - platform: adc
    pin: A0
    name: "Illuminance ${alt_name}"
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D2
    num_leds: 120
    rgb_order: GRB
    name: ${name}
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_flicker:
      - addressable_fireworks:
      - addressable_scan:
      - flicker:
      - strobe:
      - strobe:
          name: Warm White
          colors:
            - state: true
              brightness: 80%
              red: 100%
              green: 78%
              blue: 14%
              duration: 2s
            - state: true
              brightness: 80%
              red: 100%
              green: 78%
              blue: 14%
              duration: 2s
            - random:
