substitutions:
  device: led_bureau
  name: Bureau
  update_interval: 10min
esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret lan_domain
  manual_ip:
    static_ip: 192.168.0.204
    gateway: 192.168.0.1
    subnet: 255.255.255.0

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/web_server.yaml
<<: !include common/text_sensors.yaml
<<: !include common/logger.yaml
<<: !include common/binary_sensor.yaml
<<: !include common/switch.yaml
<<: !include common/sensor.yaml
  
output:
  - platform: esp8266_pwm
    id: pwm_1 
    pin: GPIO5 #RED
  - platform: esp8266_pwm
    id: pwm_2
    pin: GPIO12 #GREEN
  - platform: esp8266_pwm
    id: pwm_3 
    pin: GPIO13 #BLUE
    
light:
  - platform: rgb
    name: "Led Bureau"
    red: pwm_1
    green: pwm_2
    blue: pwm_3
    effects:
      - random
      - strobe
      - flicker