substitutions:
  device: verlichting_logeerkamer
  name: Verlichting Logeerkamer
  short_name: Logeerkamer
  update_interval: 10min

esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m

<<: !include common/common.yaml
<<: !include common/logger.yaml

<<: !include common/shelly_1.yaml