substitutions:
  device: verlichting_slaapkamer_margot
  name: Verlichting Slaapkamer Margot
  short_name: Slaapkamer Margot
  update_interval: 10min

esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m

<<: !include common/common.yaml
<<: !include common/logger.yaml

<<: !include common/shelly_1.yaml