substitutions:
  device: verlichting_gang_eerste_verdiep
  name: Verlichting Gang Eerste Verdiep
  short_name: Gang Eerste Verdiep
  update_interval: 10min

esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m

<<: !include common/common.yaml
<<: !include common/logger.yaml

<<: !include common/shelly_1.yaml