substitutions:
  device: verlichting_wc_boven
  name: Verlichting WC Boven
  short_name: WC Boven
  update_interval: 10min

esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m

<<: !include common/common.yaml
<<: !include common/logger.yaml

<<: !include common/shelly_1.yaml