substitutions:
  device: weatherstation
  name: Weather Station
  update_interval: 10min

esphome:
  name: ${device}
  platform: ESP8266
  board: nodemcuv2

<<: !include common/common.yaml
<<: !include common/logger.yaml

dallas:
  - pin: GPIO14

binary_sensor:
  - !include common/binary_sensor/status.yaml
  - platform: gpio
    pin: 
      number: GPIO2
      inverted: True
    name: "Weather Station Rain"
    device_class: moisture
    filters:
      delayed_off: 900000ms #15min

sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml
  - platform: dallas
    address: 0x5802131211A7AA28
    name: "Weather Station Temperature"
  - platform: uptime
    name: "Weather Station Uptime"
  #- platform: integration
  #  name: "Total Daily Rain"
  #  sensor: rain_meter
  #  time_unit: d
  #- platform: integration
  #  name: "Total hourly Rain"
  #  sensor: rain_meter
  #  time_unit: h
  #- platform: pulse_counter
  #  pin: D6
  #  unit_of_measurement: 'mm'
  #  name: 'Rain Meter'
  #  filters:
  #    - multiply: 1.298
  #  id: rain_meter